name: Nix Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  nix-build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        # Optional: GitHub Access Token, um Rate-Limits zu vermeiden
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Build package
      # -L zeigt detaillierte Logs an
      run: nix build -L

    - name: Prepare Artifact
      # Das Ergebnis von `nix build` ist ein Symlink ./result
      # Wir kopieren den Inhalt heraus, damit der Upload funktioniert.
      run: |
        mkdir -p build-artifacts
        cp -a result/*  build-artifacts/

    - name: Upload Binary
      uses: actions/upload-artifact@v4
      with:
        name: decanter-nix-artifacts
        path: build-artifacts
